### PR TITLE
Cleaned the English Definition of Words

### PR DESCRIPTION
**Pull request by leonfox1**
In the "English Definition" column of the "words.tsv" file, I changed the double quotes to single quotes in order to make the file "beautiful and searchable" in Github.  

I uploaded a cleaned file, pasted it into the "words.tsv" file, then deleted it from my own repository.  The "words.tsv" should be the only thing that changed.

Note that this is my first time seriously using Github, so feel free to tell me to change my process if i am doing something wrong.  Also, please be patient with my initial mistakes as I familiarize myself with how to use Github properly.

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Wonderful! Your pull request is perfect.
I was trying to use a JavaScript library to load and show the TSV nicely, but you saved me hours of work by finding out that GitHub can do it, thanks a lot :-)

**Comment by leonfox1** [comment]
Great, thanks. I figured that would be a quick win to get started. I will start looking into some of the next steps that I can work on shortly.

**Comment by nicolas-raoul** [comment]
I created an organization and made you a member.
That means that even if I am kidnapped by UFOs, you can keep maintaining the project :-)
Also, you can now merge your own pull requests.

**Comment by nicolas-raoul** [comment]
I started simplifying the English definitions, but my Chinese is poor so I will need your level-25 expertise for most of the rest ^_^

**Comment by leonfox1** [comment]
Sounds good and thanks for doing that--should the aliens get you, I will try my best to carry on this project :)  
I spent some time yesterday thinking about how to approach the cleanup.  In my former job, I used to do a lot of work cleaning data, but this type of cleanup work will probably require more manual work than I usually do.  
I like what you started, but I am thinking about splitting it into two columns, one with "Primary/Simple Definition" and one with "Alternate Possible Definitions".  That way we can keep the other material in the same general location in case we need it for correcting errors in the future, though it wouldn't publish with the Anki Deck.  
Sadly, despite FINALLY finishing the Duolingo curriculum last week, I am far from an expert.  I do have a Chinese wife that can occasionally help me with the tricky ones though.  Anyways, I will think about how to attack it some more over the next couple days, and on Monday (or at least next week), I plan to spend some more time on it.
Thanks again!

**Comment by nicolas-raoul** [comment]
> "Primary/Simple Definition" and "Alternate Possible Definitions"

Great idea!

**Comment by nicolas-raoul** [comment]
How about having two columns called "Primary definition" and "CC-CEDICT full definition"?

CC-CEDICT is the name of the dictionary where the definitions come from.
Keeping the full definition saves time compared to removing the primary definition from it.

**Comment by leonfox1** [comment]
I agree.  Let's do that.  I have got time right now for the next few hours to work on this and I can start working on the definitions.  There are 88 "Lessons" in Duolingo split into 6 "Sections".  
Section 1: 6 Lessons
Section 2: 11 Lessons
Section 3: 13 Lessons
Section 4: 15 Lessons
Section 5: 19 Lessons
Section 6: 24 Lessons

Today I should be able to get through sections 1 and 2.  After that, each section will likely take progressively longer because there is more lessons in each one and the difficulty level increases.  Anyways, I will get working on this now.

**Comment by leonfox1** [comment]
Also, as I mentioned early on, I am fairly new to Github.  What is the best place for us to have discussions like this about coordinating?  Is it right here within these Github "Conversations"?  Apologies for having to ask such a basic question...

**Comment by nicolas-raoul** [comment]
I just pushed to GitHub.
I will have no more time today so I let you edit all you want :-)

**Comment by nicolas-raoul** [comment]
Issues are a more usual place for such conversations.
Let's continue at https://github.com/anki-decks/anki-deck-for-duolingo-chinese/issues/2 :-)

**Pull request merged**
